export default{
    name:'korisnik',
    title:'Korisnik',
    type:'document',
    fields:[{
        name:'userKorisnik',
        title:'UserKorisnik',
        type:'string',
    },
    {
        name:'sifraKorisnik',
        title:'SifraKorisnik',
        type:'string',
    },
    {
        name:'titula',
        title:'Titula',
        type:'string'
    }
]
}