export default{
    name:'lek',
    title:'Lek',
    type:'document',
    fields:[{
        name:'naziv',
        title:'Naziv',
        type:'string',
    },
    {
        name:'deskripcija',
        title:'Deskripcija',
        type:'string',
    },
    {
        name:'slika',
        title:'Slika',
        type:'image'
    }  
]
}